version: '3'
services:
  dbreadconnect-docker:
    image: mysql:8.0
    restart: always
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=dbreadconnect
    volumes:
      - dbreadconnect:/var/lib/mysql
volumes:
  dbreadconnect:
